### ISSUE TITLE
Import and export of text labels in QGEP

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#552] opened 2020-02-28 15:14 UTC
**Initial situation**
In QGEP, labels are always placed automatically. For work on the screen, the iO. Labels can also be placed manually for data exchange or plan output via PDF file or plot.
In the VSA-DSS resp. in the Postgresql data model there are Txt classes with which labels for wastewater structures (manholes), postures and catchment areas can be stored in the database and then also exchanged.
For the exchange with DXF labels can be exported with the export function of QGIS.

**Data exchange with INTERLIS - Export**
The data exchange with INTERLIS, especially of the subset SIA405 waste water, is a frequent task for the data transfer of the work plan waste water to a RegioGIS. Thereby the Txt classes for wastewater structure and husbandry are used.
The database does not have to be updated every time a label is changed. It might make more sense if the user manually triggers the export of the labels to the database before an INTERLIS export. In this case the necessary information per label is written into the database for the plan type work plan (typical scale 1:500, many details) and, if necessary, also for the plan type overview plan (typical scale 1:2000, only primary sewage plants, only shaft designations and, if necessary, attitude clearance height). It is important that those labels are written to the database which the user can see on the screen with the appropriate scale (i.e. depending on the layer properties label definition).
Problem: if I define the position manually for the scale 1:500, then this is not the correct position for the scale 1:2000 or 1:5000.
The user must be able to define which labels are to be used for which scale for which plan type.
Specifically, different settings for the different attributes of the text classes are then possible and must be configurable. I have the following agreements with RegioGIS Beo:
- Text orientation in old degree, horizontal at 90 degrees, orientation in clockwise
- Character for line feed (\n)
- Substitute character for per mille character (&#8240;)

**Data exchange with INTERLIS - Import**
Basically, in my view, only the location info (textpos, textori, texthali, textvali) per class and object must be adopted. The text/text color etc. itself is taken from the label definition.

**Data exchange with DXF export**
With the QGIS command Export Project with DXF this requirement can be met in principle. The problem with this command in version 3.10.2 is that the symbol scale only applies to symbols, not to labels. The labels are exported as they are defined for a very large scale (i.e. not WYSIWYG, if I assume a scale of 1:500). This means that I have to create an own label definition for the DXF export, which is not scale dependent.
The export project to DXF should be completed in this respect.
A second problem with this command are the output layer attributes if the attribute is encoded. It should be possible to use the displayed value (represent_value).

**Data exchange with DXF import**
Is generally not relevant for QGEP. If data is to be transferred from DXF, one way or another, many manual additions are necessary. A special QGEP function is therefore not necessary.

Pendency for labels: Address of (E1), E2, E3 or (A1), A2 for several E or A with labelled code.

**Comment by sjib** [comment] 2020-02-28 15:14
#356

**Comment by sjib** [comment] 2021-01-18 19:35
@m-kuhn Could you describe what would be needed on QGIS side to get a the automatic label positions in a form, that they could be export for a specific scale including manually placed different positions?

**Comment by sjib** [comment] 2022-04-12 13:54
Detailed description here: https://gist.github.com/m-kuhn/e13adf28da35985dc8060a53f1074be9

**Comment by sjib** [comment] 2022-06-23 08:13
Needed adaptions on qgepqwat2ili: https://github.com/QGEP/qgepqwat2ili/issues/58

**Comment by sjib** [comment] 2022-06-23 08:19
First part of implementation on QGIS Upstream realized with QGIS 3.24
https://www.qgis.org/de/site/forusers/visualchangelog324/index.html?highlight=changelog#feature-extract-labels-algorithm

**Comment by sjib** [comment] 2022-10-08 04:12
Second part available for testing [WIP] https://github.com/QGEP/qgepqwat2ili/pull/73

**Comment by sjib** [comment] 2022-10-08 04:17
I get the following error when exporting:

**Comment by sjib** [comment] 2022-10-08 04:42
@olivierdalang Which layers are taken into consideration for the export of text classes? All 3 (wastewater_structure, reach and catchment) or just the ones I select?

**Comment by sjib** [comment] 2022-10-08 04:45
@olivierdalang Does the scale of the layer and the scale I select have to match for the export or does the algorithm zoom in / out to my selection(s) - kind of should, else I cannot do several at once.

If I do not see any labels in a certain scale do I get _text data or not? Or does it just get the ones visible?

**Comment by olivierdalang** [comment] 2022-10-10 09:36
> I get the following error when exporting: Leitungskataster, Werkplan

I tested again here on the demo data, and could not reproduce the issue (tried with multiple scales at once, with the scales one by one, with and without selection). Can you give more details on how to reproduce the error (exact export settings, exact selection if any, Postgres/postgis versions) ?

Looking at the error, I really don't understand what could be going on, as it seems the label position is correctly generated, and the request never sets the SRID so either it should fail all the time, or never, but not only on some scales...

> Which layers are taken into consideration for the export of text classes? All 3 (wastewater_structure, reach and catchment) or just the ones I select?

It exports both vw_qgep_wastewater and vw_qgep_reach, but not catchments. This is hardcoded and does not take layer selection into account.

> Does the scale of the layer and the scale I select have to match for the export or does the algorithm zoom in / out to my selection(s) - kind of should, else I cannot do several at once.

The current display (zoom / scale) has no impact. Only the options in the export dialog are taken into account. The algorithm indeed only exports the bounding box of the selection. Otherwise the label options are used as is, incl. scale based visibility. This means that if you export a scale where layer are not shown due to scale, they will not be exported.

> If I do not see any labels in a certain scale do I get _text data or not? Or does it just get the ones visible?

No, only visible labels get exported.

**Comment by sjib** [comment] 2022-10-10 11:29
>    No, only visible labels get exported.
I think vw_gep_wastewater_structure and vw_gep_reach do not show any labels with scales 1:5000 and 1:10'000. So that is why we do not get data and therefore no error:
![20221010_label_settings](https://user-images.githubusercontent.com/1265865/194856174-b9026d9e-1349-4f9b-a650-9cc4f71eae1a.jpg)

**Comment by sjib** [comment] 2022-10-10 11:38
> Can you give more details on how to reproduce the error (exact export settings, exact selection if any, Postgres/postgis versions) ?
Postgres 12, postgis 3.0.0
Setting see screenshot, using the qgep demodata arbon
![20221010_export_textklassen_lk](https://user-images.githubusercontent.com/1265865/194857626-79a9a320-ad69-44b6-8981-f992c872c074.jpg)

**Comment by olivierdalang** [comment] 2022-10-12 13:21
New version ready to test (https://github.com/QGEP/qgepplugin/pull/69)

**Comment by olivierdalang** [comment] 2023-03-09 09:32
closing this since implemented and merged (subsequent issues to be tracked separately)

**Closed by olivierdalang** 2023-03-09 09:32 UTC
Labels: Feature, FRP_8_Development
