### ISSUE TITLE
vw_qgep_cover and vw_qgep_reach delete

### ISSUE THREAD

**Issue by bogdanvaduva** [QGEP/QGEP#151] opened 2015-09-18 05:56 UTC
I am posting some code to be seen by others so they can comment on what I did.
Here are the issues that I had when I tried deleting elements from vw_qgep_cover and vw_qgep_reach.
First, deleting rows from vw_qgep_cover it's not allowed so I had to create a function that does that.
The code is:

```
-- Function: qgep.vw_qgep_cover_delete(character varying)

-- DROP FUNCTION qgep.vw_qgep_cover_delete(character varying);

CREATE OR REPLACE FUNCTION qgep.vw_qgep_cover_delete(id character varying)
  RETURNS boolean AS
$BODY$DECLARE mn_id character varying (500);
DECLARE wn_id character varying (500);
BEGIN
SELECT qgep.od_structure_part.fk_wastewater_structure INTO mn_id FROM qgep.od_structure_part WHERE obj_id=id;
SELECT qgep.od_wastewater_networkelement.obj_id INTO wn_id FROM qgep.od_wastewater_networkelement WHERE fk_wastewater_structure=mn_id;

DELETE FROM qgep.od_cover WHERE obj_id=id;
DELETE FROM qgep.od_manhole WHERE obj_id=mn_id;
DELETE FROM qgep.od_structure_part WHERE obj_id=id;
DELETE FROM qgep.od_wastewater_node WHERE obj_id=wn_id;
DELETE FROM qgep.od_reach_point WHERE fk_wastewater_networkelement=wn_id;
DELETE FROM qgep.od_wastewater_networkelement WHERE obj_id=wn_id;
DELETE FROM qgep.od_wastewater_structure WHERE obj_id=mn_id;

refresh materialized view qgep.vw_network_node;
refresh materialized view qgep.vw_network_segment;

RETURN true;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION qgep.vw_qgep_cover_delete(character varying)
  OWNER TO postgres;

Second deleting from vw_qgep_reach it's allowed, but when I looked in the database I saw that some values were left behind in od_channel and another few tables. I wrote another function to do the cleanup:

CREATE OR REPLACE FUNCTION qgep.vw_qgep_reach_delete(id character varying)
  RETURNS boolean AS
$BODY$DECLARE cl_id character varying (500);
DECLARE cnt integer;
BEGIN
SELECT fk_wastewater_structure INTO cl_id FROM qgep.od_wastewater_networkelement WHERE obj_id=id;


UPDATE qgep.od_wastewater_structure 
SET _usage_current=NULL, _function_hierarchic=NULL
FROM (
SELECT * 
FROM qgep.od_channel JOIN (
SELECT qgep.od_wastewater_networkelement.fk_wastewater_structure as cl_id,frm_wn.fk_wastewater_structure as frm,to_wn.fk_wastewater_structure as too
FROM qgep.od_reach 
	JOIN qgep.od_wastewater_networkelement ON qgep.od_wastewater_networkelement.obj_id=qgep.od_reach.obj_id
		JOIN qgep.od_wastewater_structure ON qgep.od_wastewater_networkelement.fk_wastewater_structure=qgep.od_wastewater_structure.obj_id
	JOIN qgep.od_reach_point as frm ON qgep.od_reach.fk_reach_point_from = frm.obj_id
		JOIN qgep.od_wastewater_networkelement as frm_wn ON frm.fk_wastewater_networkelement=frm_wn.obj_id
	JOIN qgep.od_reach_point as too ON qgep.od_reach.fk_reach_point_to = too.obj_id
		JOIN qgep.od_wastewater_networkelement as to_wn ON too.fk_wastewater_networkelement=to_wn.obj_id
WHERE qgep.od_reach.obj_id=id
) as tbl ON qgep.od_channel.obj_id=tbl.cl_id
) as tblF 
WHERE qgep.od_wastewater_structure.obj_id IN (tblF.frm,tblF.too);

DELETE FROM qgep.vw_qgep_reach WHERE obj_id=id;
DELETE FROM qgep.od_channel WHERE obj_id=cl_id;
DELETE FROM qgep.od_wastewater_networkelement WHERE obj_id=id;
DELETE FROM qgep.od_wastewater_structure WHERE obj_id=cl_id;

UPDATE qgep.od_wastewater_structure
SET _usage_current=tbl.usage_current, _function_hierarchic=tbl.function_hierarchic
FROM (
SELECT qgep.od_wastewater_structure.obj_id,r1_c.usage_current,r1_c.function_hierarchic
FROM qgep.od_wastewater_structure 
	JOIN qgep.od_wastewater_networkelement ON qgep.od_wastewater_structure.obj_id=qgep.od_wastewater_networkelement.fk_wastewater_structure
	JOIN qgep.od_reach_point ON qgep.od_reach_point.fk_wastewater_networkelement=qgep.od_wastewater_networkelement.obj_id
	LEFT JOIN qgep.od_reach as r1 ON r1.fk_reach_point_from=qgep.od_reach_point.obj_id 
		JOIN qgep.od_wastewater_networkelement as r1_wn ON r1.obj_id=r1_wn.obj_id
			JOIN qgep.od_channel as r1_c ON r1_c.obj_id=r1_wn.fk_wastewater_structure
WHERE qgep.od_wastewater_structure._function_hierarchic IS NULL
) as tbl 
WHERE qgep.od_wastewater_structure.obj_id=tbl.obj_id;

UPDATE qgep.od_wastewater_structure
SET _usage_current=tbl.usage_current, _function_hierarchic=tbl.function_hierarchic
FROM (
SELECT qgep.od_wastewater_structure.obj_id,r2_c.usage_current,r2_c.function_hierarchic
FROM qgep.od_wastewater_structure 
	JOIN qgep.od_wastewater_networkelement ON qgep.od_wastewater_structure.obj_id=qgep.od_wastewater_networkelement.fk_wastewater_structure
	JOIN qgep.od_reach_point ON qgep.od_reach_point.fk_wastewater_networkelement=qgep.od_wastewater_networkelement.obj_id
	LEFT JOIN qgep.od_reach as r2 ON r2.fk_reach_point_to=qgep.od_reach_point.obj_id
		JOIN qgep.od_wastewater_networkelement as r2_wn ON r2.obj_id=r2_wn.obj_id
			JOIN qgep.od_channel as r2_c ON r2_c.obj_id=r2_wn.fk_wastewater_structure
WHERE qgep.od_wastewater_structure._function_hierarchic IS NULL
) as tbl 
WHERE qgep.od_wastewater_structure.obj_id=tbl.obj_id;

refresh materialized view qgep.vw_network_node;
refresh materialized view qgep.vw_network_segment;

RETURN true;
END;$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION qgep.vw_qgep_reach_delete(character varying)
  OWNER TO postgres;
```

My question Is there any other way of deleting those elements from database? I followed the right path?
Thanks.

**Comment by m-kuhn** [comment] 2015-09-18 13:13
This is an important issue but we'll have to be very careful how to deal with it.

In particular, have a look at this issue https://github.com/QGEP/QGEP/issues/143

It will probably be like this: @3nids promised to implement a trigger system on QGIS side so we can ask the user for additional parameters when deleting things. Once we have this, we'll need to work on how to get these to the database.

Apart from this, refreshing the materialized view show either happen on request (there's a button implemented by one of your fellow colleagues) or there should be a dirty bit set and it should be refreshed when it's actually used. I'm afraid that refreshing it like this will add a considerable latency to operations.

Cached symbology values on the other hand should be updated immediately through triggers calling the appropriate functions (see here https://github.com/QGEP/datamodel/blob/master/06_symbology_functions.sql#L430)

**Comment by m-kuhn** [comment] 2015-09-18 13:14
Closed as duplicate of #143

**Closed by m-kuhn** 2015-09-18 13:14 UTC

**Comment by bogdanvaduva** [comment] 2015-09-18 13:18
Yes, I know there is a button for refresh, but I am using QGEP in a web based application. That's way I need the database to be as clean as possible.
Again, thanks for your quick answer.

**Comment by m-kuhn** [comment] 2015-09-19 10:10
Is editing from the web frontend possible?

**Comment by bogdanvaduva** [comment] 2015-09-19 10:15
Inserting, editing, deleting covers/reaches from web with forms.

**Comment by m-kuhn** [comment] 2015-09-19 10:15
What kind of infrastructure is involved (serverside / clientside)?

**Comment by bogdanvaduva** [comment] 2015-09-19 10:17
Tomcat/JSF, Geoserver or any WFS capable geoserver, MYSQL for the web application and POSTGIS for geo support

**Comment by m-kuhn** [comment] 2015-09-19 10:18
Is this available somewhere to have a look at?

**Comment by bogdanvaduva** [comment] 2015-09-19 10:19
Yes, I can send you an IP (user and password), but it will have to be on private

**Comment by bogdanvaduva** [comment] 2015-09-19 10:21
I have to leave now. Talk in a few hours.
