### ISSUE TITLE
typo for column dammage_end in qgep.od_damage_channel 

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#175] opened 2016-02-21 10:39 UTC

**Comment by m-kuhn** [comment] 2016-02-21 10:45
Duplicate of #153

**Closed by m-kuhn** 2016-02-21 10:45 UTC

**Comment by m-kuhn** [comment] 2016-02-21 11:05
Should be fixed an a regression test added in https://github.com/QGEP/datamodel/commit/132a294bb9e021e53e9a4a65575a27b485476a3d
