### ISSUE TITLE
error when digitizing reach

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#321] opened 2017-05-29 06:25 UTC
with the latest version from qgep-github and qgis 2.18.9 you can digitize manholes but no reaches (postgis error "Layer vw_qgep_reach: PostGIS error while adding features: FEHLER: Wert zu lang für Typ character varying(16)". i opend a ticket in qgis (16607) but it was not confirmed :-(
@m-kuhn: i think you could know where to fix, thx

**Comment by kfischerar** [comment] 2017-05-29 07:04
we installed 2.18.7 and the wizard is searching for vw_cover_open, this view doesn't exist

**Comment by m-kuhn** [comment] 2017-06-01 12:55
@kfischerar just tried to reproduce it. I could add a new reach in vw_qgep_reach and change some attributes without any problems.
Please provide exact steps how to reproduce.

**Comment by ponceta** [comment] 2017-06-01 13:07
@m-kuhn same here in https://github.com/QGEP/QGEP/issues/324 on QGIS 2.18.9, appears only when digitizing with plugin.

**Comment by m-kuhn** [comment] 2017-06-01 13:10
@ponceta can you provide the steps to reproduce?

**Comment by ponceta** [comment] 2017-06-01 14:13
open qgep, activate wizard, start data entry, create reach, validate, get error varchar 16.

**Comment by haubourg** [comment] 2017-07-21 15:14
I still have the issue using 8b1f3e0c8dacddb6764e4b1cedca263d3f917a03
which seems to embed the changes from PR #39. 
I couldn't find in it which commit solved that. Should that be reopened?

**Comment by sjib** [comment] 2017-08-08 15:45
Then this looks not like a datamodel issue. Where are we with the oid generation? Any new hints on that?

**Comment by ponceta** [comment] 2017-10-04 08:17
Actually I thought this was fixed, I can provide dump and qgis project if required.

**Comment by m-kuhn** [comment] 2017-10-04 08:19
Let me have a look this afternoon, if I don't succeed to reproduce, I'll need a dump

**Comment by max-trolliet** [comment] 2017-10-04 08:26
Just tried it with my data, did not put all the attributes I could have but still, the reach is created when I exit the edit mode. 

I just can't use the wizard right now, have to get why the plugin does not work on my install (just re-installed everything...)

**Comment by ponceta** [comment] 2017-10-11 07:29
@kfischerar is it fixed for you?

@max-trolliet this issue appears only when digitizing with the wizard, without wizard, you will lose topological link between entities node_from, node_to (although geometric topo is correct)

**Comment by haubourg** [comment] 2017-10-31 13:55
@ponceta issue is fixed for you now?  The issue was data dependant right, default value in PG?

**Comment by m-kuhn** [comment] 2017-10-31 14:01
A new plugin release (0.7.0) should be out every minute, please reopen if issues persist.

**Comment by ponceta** [comment] 2017-10-31 15:07
There is no error anymore but oids are not gathered anymore from wastewaterstructures

**Comment by ponceta** [comment] 2017-10-31 15:11
https://youtu.be/FgdBFFXKewQ

**Comment by ponceta** [comment] 2017-10-31 15:23
@m-kuhn I can't reopen this since you closed this as royal admin and I'm only a peasant git user. ;)

**Comment by ponceta** [comment] 2017-10-31 15:33
Ok I'm too stupid, you can close this. ;)

**Comment by ponceta** [comment] 2017-10-31 15:34
I was considering identifiers instead of obj_id

**Comment by m-kuhn** [comment] 2017-10-31 15:35
I was just going trying to find the right questions to ask, all good in this case :+1:

**Comment by ponceta** [comment] 2017-10-31 15:35
![image](https://user-images.githubusercontent.com/8614223/32232941-7dce9d42-be59-11e7-96c9-ab3c0c989c10.png)

**Closed** 2017-10-31 15:35 UTC
Labels: Datamodel, Error
