### ISSUE TITLE
Reach points and wastewater_network element are not removed at reach removal

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#436] opened 2018-07-18 08:01 UTC
When removing a reach using qgep_od.wv_qgep_reach

![qgep_reach_points](https://user-images.githubusercontent.com/8614223/42867847-07129a52-8a71-11e8-8bda-d97b5aa363eb.gif)

Removing a reach should also remove:
- [ ] Reach point (From)
- [ ] Reach point (To)
- [ ] wastewater_networkelement

Reach points are created and updated simultaneously with reaches, they should disapear with it right?

Generally related to :
https://github.com/QGEP/QGEP/issues/143

**Comment by m-kuhn** [comment] 2018-07-23 08:42
Confirmed, reach points need to be deleted with reaches. If this is not the case, then it's a bug.

**Comment by ponceta** [comment] 2018-12-14 09:21
It's a bug : 

There's something wrong with the RULE execution:

```
CREATE OR REPLACE RULE vw_qgep_reach_on_delete AS
    ON DELETE TO qgep_od.vw_qgep_reach DO INSTEAD ( 
  DELETE FROM qgep_od.reach
  WHERE reach.obj_id::text = old.obj_id::text;
 DELETE FROM qgep_od.wastewater_networkelement
  WHERE wastewater_networkelement.obj_id::text = old.obj_id::text;
 DELETE FROM qgep_od.reach_point
  WHERE reach_point.obj_id::text = old.rp_from_obj_id::text;
 DELETE FROM qgep_od.reach_point
  WHERE reach_point.obj_id::text = old.rp_to_obj_id::text;
);
```

It's linked to the execution order.

**Comment by signedav** [comment] 2019-01-07 07:47
I tested that and I can confirm the issue.

Still I couldn't find out why the rule is not working, because all I see is correct.

Anyway is there a reason for not using a trigger here? 
Since mostly one row is deleted per transaction I don't see a performance loss when using triggers.

**Comment by ponceta** [comment] 2019-01-10 13:09
> I tested that and I can confirm the issue.

:+1: 

> Still I couldn't find out why the rule is not working, because all I see is correct.

Same conclusion here in Pully

> Anyway is there a reason for not using a trigger here?

At the time, I raised an issue [here](https://github.com/QGEP/QGEP/issues/372)
Not having same approach on wastewater_structures and reaches does not make sense.

> Since mostly one row is deleted per transaction I don't see a performance loss when using triggers.

QWAT edition model is almost always using insert / update / delete triggers and we didn't encounter any performance issue yet.

**Comment by m-kuhn** [comment] 2019-01-16 08:46
Fixed in https://github.com/QGEP/datamodel/pull/87

**Closed by m-kuhn** 2019-01-16 08:46 UTC
Labels: P1
