### ISSUE TITLE
Special structures (weirs, retention,..) and export to SWMM

### ISSUE THREAD

**Issue by TriformMoritz** [QGEP/QGEP#719] opened 2022-01-25 10:13 UTC
It is crucial to easily to digitize and describe hydraulically special structure and export them for modeling, for this these points should be supported:

- Description of the hydraulic structure like in appendix  3 of the VSA-wiki (https://vsa.ch/fr/wiki/ ),  "Guide des données de l’assainissement urbain", chapter 2.3
- Documentation of how to enter each of these special structures in TEKSI wastewater
- Automatic export to SWMM of these special structures.

**Comment by sjib** [comment] 2022-03-02 12:37
- [x] `Automatic export to SWMM of these special structures` - is supporte in  [13_vw_swmm_storages.sql](https://github.com/QGEP/datamodel/blob/master/swmm_views/13_vw_swmm_storages.sql#L35) and [02_vw_swmm_junctions.sql](https://github.com/QGEP/datamodel/blob/master/swmm_views/02_vw_swmm_junctions.sql)

@TriformMoritz Do you need any others? -- 5372 -- "stormwater_overflow"?

**Comment by TriformMoritz** [comment] 2022-03-03 10:24
I am not able to model anything different than a very simple weir inside QGEP yet. For example (BEP):
https://vsa.ch/fr/wiki/3-2-13-bassin-deaux-pluviales-bassin-de-decantation-en-connexion-laterale/

I am not able to tell to tell how to model this (I tried) in QGEP
- I cannot connect two or more "main" nodes.
- If I connect a main node, I am not able to make a detailed geometry (and I don't know to which node).
- Two or more weirs are difficult.
- The way documented by Urs works (for one weir) but is very difficult and not at all intuitive.

Please try yourself, I gave up after two hours.

The export to SWMM comes afterward.
Concerning the SWMM export:
- Curves are supported in VSA-DSS (HQ-Relations), so they should also be imported into SWMM-> **Weir curves**, I don't think tidal curves are yet supported in VSA-DSS.
- Flow_valves (Limitateur_debit) are supported in VSA-DSS, so they should also be imported into SWMM-> **Control curves**.
- I am not sure if storage curves are supported in VSA-DSS.

**Comment by urskaufmann** [comment] 2022-03-05 21:22
I have documented, how to construct the VSA-example 3.2.13
There is one real problem with the obj_id, that are automatic set as last_value+"-1" and therefor are to long (see also Issue #619 )
[VSA Example 3-2-13 in QGEP.docx](https://github.com/QGEP/QGEP/files/8191494/VSA.Example.3-2-13.in.QGEP.docx)

There should be a new vw_overflow_line. And the network following should work also with this overflows.

**Comment by TriformMoritz** [comment] 2022-03-07 13:23
My first problem: I cannot digitize, the error say : "Ajouter partie" at the end of my digitizing try:
![image](https://user-images.githubusercontent.com/33837122/157041955-e60d9aa9-fa97-4fe4-99c7-813301e38c46.png)
![image](https://user-images.githubusercontent.com/33837122/157042377-6747fbfc-c32c-4ba8-b6a7-6f2d5fed6ee3.png)

**Comment by sjib** [comment] 2022-03-07 16:38
I tried with two different projects I have - with the first one I get the same error as @TriformMoritz - with the other digitizing a detailed_geometry works fine. It is on the same database.  The first node is within the network. The one that works is at the end (Vorflutereinlauf). When I try in that project file on a node within the network it also fails. So it looks not like a problem of the project file version. In German the message is `2022-03-07T16:59:52     WARNING    Teil hinzufügen`

**Comment by sjib** [comment] 2022-03-07 16:48
Found some information here: https://github.com/qgis/QGIS/issues/41294 that has been fixed in 3.20 (https://github.com/qgis/QGIS/pull/41391). @TriformMoritz Can you check with the latest LTR 3.24 if this still happens?

**Comment by sjib** [comment] 2022-03-07 17:07
And this hint in the documentation:
`If the geometry disappears after digitizing or if you get an message (like ‘Add part’), you have probably tried to digitize over a catchment area (or an other polygon theme) and the layer has set the avoid overlap option in the snapping settings. Do change the avoid overlap settings.`

Very bottom of https://qgep.github.io/docs/user-guide/digitizing/digitizingdetailedgeometry.html

And here a screenshot of Snapping settings: In 3.24 it now gets more information - maybe you find out why it is invalid.

![digitizing_test_20220221_2_qgep_v202112_3 24](https://user-images.githubusercontent.com/1265865/157082470-f1a0d96d-a437-4e93-b27c-d7eca75e067e.jpg)

**Comment by TriformMoritz** [comment] 2022-03-07 17:36
Works, thank you! The error message (of QGIS) should be clearer, like -> "Overlapping not allowed in snapping options" or "les options d'accrochage empèchent la création de la géométrie"

**Comment by urskaufmann** [comment] 2022-03-07 20:39
Add part-error: Stefan showed the solution. See also  Issue #628

**Comment by TriformMoritz** [comment] 2022-03-08 08:04
So it worked (I actually had all the weirs defined already, but they weren't visible and not exported to SWMM so I could not check), thank you Urs for the view!:
![image](https://user-images.githubusercontent.com/33837122/157091427-034c60ce-8273-4267-8d1a-0fd8412e8f7e.png)

I would propose:
1. Make the view editable -> Possibility to draw a weir line (and fill out the attributes), either in the wizard or in the edition of the view (like the line catchment to node). -> New feature in QGEP
2. Correct the OID error documented by urs (https://github.com/QGEP/QGEP/issues/619 )
3. Export to SWMM of weirs, storage units and dividers. -> New feature in SWMM

**Comment by tproduit** [comment] 2022-04-20 11:52
> * I am not sure if storage curves are supported in VSA-DSS.

@sjib Are they supported? Do they exist in QGEP?

**Comment by sjib** [comment] 2022-04-20 12:48
Hydraulic classes in VSA-DSS

![hydraulic_classes_dss](https://user-images.githubusercontent.com/1265865/164231097-193deb92-ccb2-46cd-8f93-4bab2c62ee24.jpg)


hq_relation and overflow_char (Ueberlaufchrakteristik) have the parameters needed for the SWMM curves (see chapter C.5 and 3.28. of the [SWMM 5.2. User manual](https://www.epa.gov/system/files/documents/2022-02/storm-water-management-model-users-manual-version-5.2.pdf)

![c5 curve editor](https://user-images.githubusercontent.com/1265865/164232996-22e8a6bc-8221-40fc-be13-53cd68f46ce9.jpg)

Check whethe only Q-H relations are supported or also Q-Q relations (overflow_char.kind_overflow_char

**Comment by tproduit** [comment] 2022-05-18 05:37
Feedback from technical user group (2022.05.18)
In the corresponding QGIS form a tab "overview" could be created to ease the exploration.

**Comment by ponceta** [comment] 2023-03-14 06:07
@TriformMoritz is there anything more action to do here?

**Closed** 2024-12-20 21:16 UTC
Labels: Feature, SWMM

**Comment by TriformMoritz** [comment] 2024-12-24 09:15
Hello,
Did anyone try do digitilize and export a special structure and tested if it
-works (including export)?
-Is easy and intuitive to do?
 Or should we better do this in the TEKSI 2020 version and leave it like this in 2015?

**Comment by TriformMoritz** [comment] 2025-10-06 14:09
Hello, trying to digitze a rectangular easy around a wastewater structuregéométrie and got this erreur:
  "Ajouter une partie : L'entité ne peut pas être ajoutée car sa géométrie s'est réduite en raison de l'évitement d'intersection"

<img width="1281" height="606" alt="Image" src="https://github.com/user-attachments/assets/954bf5b2-a0d8-441c-bca8-2dc58b110fe1" />

I do not understand the cause. Anyone does?

**Comment by sjib** [comment] 2025-10-06 17:38
No problem with TEKSI tww:

<img width="1920" height="1143" alt="Image" src="https://github.com/user-attachments/assets/3d9639dc-6cb9-4a6b-84a4-31891c7668d6" />

<img width="477" height="319" alt="Image" src="https://github.com/user-attachments/assets/68bccca1-d034-491e-8bf5-3fcc840c6b5d" />

**Comment by urskaufmann** [comment] 2025-10-06 20:08
I think you can have the same problem with tww. The problem is the snapping_property of QGIS. If you have overlap-options set to Follow Advanced Configuration and you digitize your special_structure in a catchment_area (which is set to Avoid overlap), QGIS will show you this message...
