### ISSUE TITLE
od_file identifier is too short

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#286] opened 2017-03-02 10:33 UTC
40 chars isn't enough to store long file names such as '8_1_3_18072013_083842_A_130718_083936.JPG'

temporary fix in https://github.com/QGEP/datamodel/commit/66ee4cc2735fcbe3be546df418b249206025deb0

**Comment by sjib** [comment] 2017-03-07 16:21
Ok, good for now.

**Comment by m-kuhn** [comment] 2017-04-21 11:25
Duplicate of #242

**Closed by m-kuhn** 2017-04-21 11:25 UTC
Labels: Datamodel
