### ISSUE TITLE
Visual feedback for snapping

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#129] opened 2015-08-04 06:44 UTC
Hi,
For 2.10 and master I'm encountering snapping problems.
The problems only show up for newly created features that are in a view (pertinent for our setup).
I can snap without problems to features already present in the view, but for example, after creating a point in the vw_qgep_cover, I cannot snap to that point, all the others already existing show no problem. I tried changing snapping options, only a reopening of the project solves it.
Am I the only one encountering this? I'm using Debian 8.

Thank you

**Comment by tudorbarascu** [comment] 2015-08-04 10:44
Just realized that we're supposed to add features using the QGEP data entry.
However, there is a small glitch in that the user doesn't get any feedback that the reach will jump to the point. The user sees that the line is snapped afterwards. Moreover, it would be nice if the plugin would have snapping settings.

**Comment by andreasneumann** [comment] 2015-08-04 11:26
Hi Tudor - yes, we are aware of the problem. Apparently it isn't this easy to fix. Snapping is active, but visual snap feedback is missing.

Let's keep this issue open until it is fixed.

Andreas

**Comment by m-kuhn** [comment] 2015-08-05 14:09
There is an upstream issue, that the digitizing maptools are not part of the public API. So there are two possibilities:

 * Reimplement all the functionality (partly done now, would also require advanced digitizing etc. not sure it's the road to follow)
 * Make the maptools available in the public API (@3nids any idea what is missing)

**Comment by 3nids** [comment] 2015-08-06 06:26
For me, not much is missing. Although, a good brainstorming would be interesting prior to moving maptools to core (event in map coordinate, manual triggering of events, etc.).

**Comment by m-kuhn** [comment] 2015-08-06 11:36
We've been presenting at Uster today and construction tools have explicitly been requested. IMO we should push this to a higher prio.

**Comment by andreasneumann** [comment] 2015-08-06 13:01
I agree - it would be good to implement this with high priority. Let me know if/how we can help.

**Comment by m-kuhn** [comment] 2016-08-30 08:58
@tudorbarascu is this fixed?

**Comment by m-kuhn** [comment] 2016-08-30 08:58
If not, it should be on track with QGIS 3.

**Comment by tudorbarascu** [comment] 2016-09-01 06:50
@m-kuhn It's still present.

**Comment by sjib** [comment] 2017-01-16 16:12
@m-kuhn Something that can be done now or only with QGIS3.0? Then add that label and move it to milestone August 31st, 2017.

**Comment by haubourg** [comment] 2017-04-27 13:36
Hi, I think this is fixed in 2.18.

**Comment by olivierdalang** [comment] 2020-02-13 15:34
From what I understood, I think the issue is gone, at least here snapping seems to work well with correct visual feedback incl. with newly digitized features in the views.

The only thing I see is strange default snapping options in the provided qgis project (it snaps to vw_individual_surface and catchment_area, while I guess we want to snap to vw_qgep_wastewater_structure).

**Comment by urskaufmann** [comment] 2020-02-13 15:47
This should not be a default snapping option. When I added the individual surface and catchment area to the demo project, I did test with this snapping options.
For the plugin-tools (wizard, network-following etc) is the snapping defined with the tools. Because you digitize catchment areas/individual surface with qgis-tools you have to define the wanted snapping options yourself.

**Comment by m-kuhn** [comment] 2020-02-13 16:18
Thanks everyone, let's close this issue in this case.

**Closed by m-kuhn** 2020-02-13 16:18 UTC
Labels: P1, QGIS Upstream
