### ISSUE TITLE
inserting a wastewater structure tries to insert multipoint in point geometry for vw_wastewater_node

### ISSUE THREAD

**Issue by haubourg** [QGEP/QGEP#258] opened 2016-12-09 08:22 UTC
so database constraints fail:
```
Couche vw_qgep_wastewater_structure: Erreur PostGIS lors de l'ajout d'entité : ERROR: Geometry type (MultiPoint) does not match column type (Point) CONTEXT: SQL statement "INSERT INTO qgep.vw_wastewater_node( obj_id , backflow_level , bottom_level , situation_geometry , identifier , remark , last_modification , fk_dataowner , fk_provider , fk_wastewater_structure ) VALUES ( NEW.wn_obj_id , NEW.backflow_level , NEW.bottom_level , NEW.situation_geometry , COALESCE(NULLIF(NEW.wn_identifier,''), NEW.identifier) , NEW.wn_remark , NOW() , COALESCE(NULLIF(NEW.wn_fk_provider,''), NEW.fk_provider) , COALESCE(NULLIF(NEW.wn_fk_dataowner,''), NEW.fk_dataowner) , NEW.obj_id )" PL/pgSQL function qgep.vw_qgep_wastewater_structure_insert() line 166 at SQL statement 

```

I'm using the demo dataset and project

**Comment by m-kuhn** [comment] 2016-12-15 12:49
I think this should be fixed since https://github.com/QGEP/datamodel/commit/06fafcfd90d55a843f531f4067317745d4f4347f

Are you sure you are not working with an old model?

**Comment by m-kuhn** [comment] 2016-12-15 12:50
Duplicate of https://github.com/QGEP/QGEP/issues/243

Please reopen if this is still an issue

**Closed by m-kuhn** 2016-12-15 12:50 UTC
