### ISSUE TITLE
Errors Export Interlis with QGEP 1.6.3

### ISSUE THREAD

**Issue by urskaufmann** [qgep/QGEP#872] opened 2024-10-02 07:55 UTC
**Describe the bug**
Export with option DSS 2015: Everything passes, no errors from ilivalidator, but GEP-Checker says: TOPOLOGY PAA Leitungen müssen Knoten_von und Knoten_nach Attribut haben. 
And in fact: there is no Abwassernetzelementref with the Haltungspunkt in the xtf-file and there is in schema pg2ili_dss, table haltungspunkt, field abwassernetzelementref are just null values. (but networkfollowing works >> there are all fk_networkelement ok in the database).

Export of the same database with SIA405: Error while exporting: 
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey" DETAIL:  Key (abwasserbauwerkref)=(5357) is not present in table "abwasserbauwerk". (Background on this error at: http://sqlalche.me/e/13/gkpj) 
The reason is obviously, that I have ARA-Bauwerk-records (Kleinkläranlagen).
If I export form the same database with a selection, then I have no errors and I have abwassernetzelementref with my reachpoints as expected.

**Expected behavior**
Export that works.

**Desktop (please complete the following information):**
 - QGEP plugin version 1.63
 - QGEP datamodel version 1.61
 - QGEP project file version -
 - QGIS Version 3.34.10
 - OS Win10

**Comment by sjib** [comment] 2024-10-03 15:05
@urskaufmann I am not sure if there is an adaption needed now?

- [ ] Do we need to change something in the export configuration?
- [ ] Or in the CHECK_FP constraints of CHECKVSA?
- [ ] Or just update the documentation?

**Comment by urskaufmann** [comment] 2024-10-03 15:20
That must be a simply mistake in the DSS-export.py: If I export DSS -> Haltungspunkt.Abwassernetzelementref = NULL,
If I export SIA405 -> Haltungspunkt.Abwassernetzelementref is OK

The other problem with ARA_Bauwerk seems to be solved with DSS-Export, but not in SIA405-Export.

**Comment by sjib** [comment] 2024-10-04 13:56
Maybe this is the problem - I have to check on that

```
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:Exporting QGEP.reach_point -> ABWASSER.haltungspunkt, ABWASSER.metaattribute
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - Subset ID's '[]'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - fremdschluesselstr 'ch080qwzAK000013'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - 'ch080qwzAK000013' is not in subset - replaced with None instead!
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - Subset ID's '[]'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - fremdschluesselstr 'ch080qwzAK000011'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - 'ch080qwzAK000011' is not in subset - replaced with None instead!
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - Subset ID's '[]'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - fremdschluesselstr 'ch080qwzAK000011'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - 'ch080qwzAK000011' is not in subset - replaced with None instead!
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - Subset ID's '[]'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - fremdschluesselstr 'ch080qwzAK000001'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - 'ch080qwzAK000001' is not in subset - replaced with None instead!
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - Subset ID's '[]'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - fremdschluesselstr 'ch080qwzAK001117'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - 'ch080qwzAK001117' is not in subset - replaced with None instead!
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - Subset ID's '[]'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - fremdschluesselstr 'ch080qwzAK000019'
2024-10-04T15:53:10        qgepplugin.qgepqwat2ili.qgepqwat2ili.utils:check_fk_in_subsetid - 'ch080qwzAK000019' is not in subset - replaced with None instead!
```

**Comment by urskaufmann** [comment] 2024-10-04 13:59
Why does it work with SIA405, but not with DSS?

**Comment by sjib** [comment] 2024-10-04 14:02
I have to compare the two configurations - maybe I did not adapt everything

**Comment by sjib** [comment] 2024-10-04 18:16
`check_fk_in_subsetid` needs to be adapted so it also works when having a selection - now we set fk to null - that is not what we wanted

**Comment by sjib** [comment] 2024-10-04 18:49
> Export of the same database with SIA405: Error while exporting:
> sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "abwassernetzelement" violates foreign key constraint "abwassernetzelement_abwasserbauwerkref_fkey" DETAIL: Key (abwasserbauwerkref)=(5357) is not present in table "abwasserbauwerk". (Background on this error at: http://sqlalche.me/e/13/gkpj)
> The reason is obviously, that I have ARA-Bauwerk-records (Kleinkläranlagen).

@urskaufmann The problem is that SIA405 Abwasser does not include ARABauwerk - these can only be exported with VSA-DSS

So I have to check whether fk_abwasserbauwerk is on a abwasserbauwerk subclass, that is integrated in SIA405 Abwasser (Kanal, Normschacht, Spezialbauwerk, Versickerungsanlage, Einleitstelle) but not ARABauwerk, KLARA and AbflussloseToilette

**Comment by sjib** [comment] 2024-10-04 19:28
see https://github.com/QGEP/qgepqwat2ili/pull/163/commits/2b9dbb2c5666535a91ef2fa1c9da1b56901deb44

**Comment by sjib** [comment] 2024-10-04 21:47
Test version with fix for this see https://github.com/QGEP/qgepqwat2ili/pull/163

**Comment by urskaufmann** [comment] 2024-10-06 19:12
when I replace just qgepdss/export.py, then Haltungspunkt has a Abwassernetzelementref: Works

when I replace also the other 4 files, I get error when starting the sia405 export:
Error: Could not load qgepqwat2ili due to unmet dependencies. See logs for more details. And Protokoll/qgep:  qgepplugin:No module named 'QgisModelBaker.libs.modelbaker'


I have modelbaker 7.0.3 isntalled

**Comment by sjib** [comment] 2024-10-11 13:19
Related to https://github.com/QGEP/qgepqwat2ili/pull/160

**Closed as completed** 2024-10-14 14:01 UTC
Labels: INTERLIS Export, Critical, bug
