### ISSUE TITLE
Removing qgep.vw_qgep_reach does not remove qgep.od_channel

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#374] opened 2017-11-14 12:53 UTC
This is probably an understanding question or a missing rule.

Inserting and creating a reach in qgep creates an od_channel object associated to store specific channel attributes (if I understand it right).

But when removing a reach, the associated channel is not removed.

In https://github.com/QGEP/datamodel/blob/master/view/vw_qgep_reach.sql#L420-L425 we have

```
CREATE OR REPLACE RULE vw_qgep_reach_on_delete AS ON DELETE TO qgep.vw_qgep_reach DO INSTEAD (
  DELETE FROM qgep.od_reach WHERE obj_id = OLD.obj_id;
  DELETE FROM qgep.od_wastewater_networkelement WHERE obj_id = OLD.obj_id;
  DELETE FROM qgep.od_reach_point WHERE obj_id = OLD.rp_from_obj_id;
  DELETE FROM qgep.od_reach_point WHERE obj_id = OLD.rp_to_obj_id;
);
```

**Comment by urskaufmann** [comment] 2017-11-14 13:14
the same as in #333

**Comment by m-kuhn** [comment] 2017-11-15 15:48
Closing as duplicate of #333

**Closed by m-kuhn** 2017-11-15 15:48 UTC
